# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30bfb4e34fc681da67699d6b0d7d9340"
application_url = "https://moss-valley-granted-valium.trycloudflare.com"
embedded = true
name = "remix-new"
handle = "remix-new"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://moss-valley-granted-valium.trycloudflare.com/auth/callback",
  "https://moss-valley-granted-valium.trycloudflare.com/auth/shopify/callback",
  "https://moss-valley-granted-valium.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "ronak-test-store.myshopify.com"
automatically_update_urls_on_dev = true
